---
title: "ep BH procedure Setting 3"
author: "Ethan Naegele"
date: "2024-05-12"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Setting 3 function


```{r}
run_ep_method1_setting3_simulation <- function(a_vec = c(2, 4, 6, 8, 10), 
                                               alpha = .05,
                                               exponent = .5,
                                               num_iter = 500){
result_vec_power <- c()
result_vec_fdr <- c()
for (amp in a_vec){
  result <- run_ep_method1_simulation(n = 1000,
                                          d = 100,
                                          a = amp, 
                                          num_true_sigs = 20,
                                          alpha = alpha,
                                          exponent = exponent,
                                          num_iter = num_iter)
  result_vec_power <- c(result_vec_power, result$power)
  result_vec_fdr <- c(result_vec_fdr, result$fdr)
}
return(data.frame(a = a_vec, power = result_vec_power, fdr = result_vec_fdr))
}
```

# Setting 3 simulations

```{r}
ep_method1_0_setting3 <- run_ep_method1_setting3_simulation(exponent = 0)
```

```{r}
ep_method1_1_16_setting3 <- run_ep_method1_setting3_simulation(exponent = 1/16)
```

```{r}
ep_method1_1_8_setting3 <- run_ep_method1_setting3_simulation(exponent = 1/8)
```


```{r}
ep_method1_1_4_setting3 <- run_ep_method1_setting3_simulation(exponent = 1/4)
```


```{r}
ep_method1_3_4_setting3 <- run_ep_method1_setting3_simulation(exponent = 3/4)
```

```{r}
ep_method1_9_10_setting3 <- run_ep_method1_setting3_simulation(exponent = 9/10)
```

```{r}
ep_method1_1_setting3 <- run_ep_method1_setting3_simulation(exponent = 1)
```

# Setting 3 graphs


```{r}
# Setting 3 Power
ggplot(ep_method1_0_setting3, aes(x = a, y = power)) + 
  geom_line(color = 'red') +
  geom_point(shape = 4, color = 'red') + 
  scale_y_continuous(limits = c(0, 1)) +
  labs(x = 'Signal Strength - Amplitude', y = 'Simulated Power', title = 'ep Method 1 Setting 3 Results - exponent = 0 (n = 1000, d = 100, k = 20)')
```



```{r}
# Setting 3 FDR
ggplot(ep_method1_0_setting2, aes(x = a, y = fdr)) + 
  geom_line(color = 'red') +
  geom_point(shape = 4, color = 'red') + 
  scale_y_continuous(limits = c(0, .15)) +
  labs(x = 'Signal Strength - Amplitude', y = 'Simulated FDR', title = 'ep Method 1 Setting 3 Results - exponent = 0 (n = 1000, d = 100, k = 20)')
```


```{r}
# Setting 3 Power
ggplot(ep_method1_1_16_setting3, aes(x = a, y = power)) + 
  geom_line(color = 'red') +
  geom_point(shape = 4, color = 'red') + 
  scale_y_continuous(limits = c(0, 1)) +
  labs(x = 'Signal Strength - Amplitude', y = 'Simulated Power', title = 'ep Method 1 Setting 3 Results - exponent = 1/16 (n = 1000, d = 100, k = 20)')
```


```{r}
# Setting 3 FDR
ggplot(ep_method1_1_16_setting2, aes(x = a, y = fdr)) + 
  geom_line(color = 'red') +
  geom_point(shape = 4, color = 'red') + 
  scale_y_continuous(limits = c(0, .15)) +
  labs(x = 'Signal Strength - Amplitude', y = 'Simulated FDR', title = 'ep Method 1 Setting 3 Results - exponent = 1/16 (n = 1000, d = 100, k = 20)')
```


```{r}
# Setting 3 Power
ggplot(ep_method1_1_8_setting3, aes(x = a, y = power)) + 
  geom_line(color = 'red') +
  geom_point(shape = 4, color = 'red') + 
  scale_y_continuous(limits = c(0, 1)) +
  labs(x = 'Signal Strength - Amplitude', y = 'Simulated Power', title = 'ep Method 1 Setting 3 Results - exponent = 1/8 (n = 1000, d = 100, k = 20)')
```

```{r}
# Setting 3 FDR
ggplot(ep_method1_1_8_setting2, aes(x = a, y = fdr)) + 
  geom_line(color = 'red') +
  geom_point(shape = 4, color = 'red') + 
  scale_y_continuous(limits = c(0, .15)) +
  labs(x = 'Signal Strength - Amplitude', y = 'Simulated FDR', title = 'ep Method 1 Setting 3 Results - exponent = 1/8 (n = 1000, d = 100, k = 20)')
```


```{r}
# Setting 3 Power
ggplot(ep_method1_1_4_setting3, aes(x = a, y = power)) + 
  geom_line(color = 'red') +
  geom_point(shape = 4, color = 'red') + 
  scale_y_continuous(limits = c(0, 1)) +
  labs(x = 'Signal Strength - Amplitude', y = 'Simulated Power', title = 'ep Method 1 Setting 3 Results - exponent = 1/4 (n = 1000, d = 100, k = 20)')
```

```{r}
# Setting 3 FDR
ggplot(ep_method1_1_4_setting2, aes(x = a, y = fdr)) + 
  geom_line(color = 'red') +
  geom_point(shape = 4, color = 'red') + 
  scale_y_continuous(limits = c(0, .15)) +
  labs(x = 'Signal Strength - Amplitude', y = 'Simulated FDR', title = 'ep Method 1 Setting 3 Results - exponent = 1/4 (n = 1000, d = 100, k = 20)')
```



```{r}
# Setting 3 Power
ggplot(ep_method1_3_4_setting3, aes(x = a, y = power)) + 
  geom_line(color = 'red') +
  geom_point(shape = 4, color = 'red') + 
  scale_y_continuous(limits = c(0, 1)) +
  labs(x = 'Signal Strength - Amplitude', y = 'Simulated Power', title = 'ep Method 1 Setting 3 Results - exponent = 3/4 (n = 1000, d = 100, k = 20)')
```


```{r}
# Setting 3 FDR
ggplot(ep_method1_3_4_setting2, aes(x = a, y = fdr)) + 
  geom_line(color = 'red') +
  geom_point(shape = 4, color = 'red') + 
  scale_y_continuous(limits = c(0, .15)) +
  labs(x = 'Signal Strength - Amplitude', y = 'Simulated FDR', title = 'ep Method 1 Setting 3 Results - exponent = 3/4 (n = 1000, d = 100, k = 20)')
```

```{r}
# Setting 3 Power
ggplot(ep_method1_9_10_setting3, aes(x = a, y = power)) + 
  geom_line(color = 'red') +
  geom_point(shape = 4, color = 'red') + 
  scale_y_continuous(limits = c(0, 1)) +
  labs(x = 'Signal Strength - Amplitude', y = 'Simulated Power', title = 'ep Method 1 Setting 3 Results - exponent = 9/10 (n = 1000, d = 100, k = 20)')
```


```{r}
# Setting 3 FDR
ggplot(ep_method1_9_10_setting2, aes(x = a, y = fdr)) + 
  geom_line(color = 'red') +
  geom_point(shape = 4, color = 'red') + 
  scale_y_continuous(limits = c(0, .15)) +
  labs(x = 'Signal Strength - Amplitude', y = 'Simulated FDR', title = 'ep Method 1 Setting 3 Results - exponent = 9/10 (n = 1000, d = 100, k = 20)')
```


```{r}
# Setting 3 Power
ggplot(ep_method1_1_setting3, aes(x = a, y = power)) + 
  geom_line(color = 'red') +
  geom_point(shape = 4, color = 'red') + 
  scale_y_continuous(limits = c(0, 1)) +
  labs(x = 'Signal Strength - Amplitude', y = 'Simulated Power', title = 'ep Method 1 Setting 3 Results - exponent = 1 (n = 1000, d = 100, k = 20)')
```


```{r}
# Setting 3 FDR
ggplot(ep_method1_1_setting2, aes(x = a, y = fdr)) + 
  geom_line(color = 'red') +
  geom_point(shape = 4, color = 'red') + 
  scale_y_continuous(limits = c(0, .15)) +
  labs(x = 'Signal Strength - Amplitude', y = 'Simulated FDR', title = 'ep Method 1 Setting 3 Results - exponent = 1 (n = 1000, d = 100, k = 20)')
```







