---
title: "ep-BH cutoff setting 2"
author: "Ethan Naegele"
date: "2024-05-26"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
run_ep_method1_cutoff_setting2_simulation <- function(a_vec = c(2, 4, 6, 8, 10), 
                                               alpha = .05,
                                               cutoff = .2,
                                               num_iter = 500){
result_vec_power <- c()
result_vec_fdr <- c()
for (amp in a_vec){
  result <- run_ep_method1_cutoff_simulation(n = 500,
                                          d = 50,
                                          a = amp, 
                                          num_true_sigs = 10,
                                          alpha = alpha,
                                          cutoff = cutoff,
                                          num_iter = num_iter)
  result_vec_power <- c(result_vec_power, result$power)
  result_vec_fdr <- c(result_vec_fdr, result$fdr)
}
return(data.frame(a = a_vec, power = result_vec_power, fdr = result_vec_fdr))
}
```


```{r}
set.seed(12)
ep_method1_cutoff_.1_setting2_v2 <- run_ep_method1_cutoff_setting2_simulation(cutoff = .1)
```

```{r}
set.seed(12)
ep_method1_cutoff_.2_setting2_v2 <- run_ep_method1_cutoff_setting2_simulation(cutoff = .2)
```


```{r}
set.seed(12)
ep_method1_cutoff_.3_setting2_v2 <- run_ep_method1_cutoff_setting2_simulation(cutoff = .3)
```


```{r}
set.seed(12)
ep_method1_cutoff_.4_setting2_v2 <- run_ep_method1_cutoff_setting2_simulation(cutoff = .4)
```

```{r}
set.seed(12)
ep_method1_cutoff_.5_setting2_v2 <- run_ep_method1_cutoff_setting2_simulation(cutoff = .5)
```

```{r}
set.seed(12)
ep_method1_cutoff_.6_setting2_v2 <- run_ep_method1_cutoff_setting2_simulation(cutoff = .6)
```

```{r}
set.seed(12)
ep_method1_cutoff_.7_setting2_v2 <- run_ep_method1_cutoff_setting2_simulation(cutoff = .7)
```


```{r}
set.seed(12)
ep_method1_cutoff_.8_setting2_v2 <- run_ep_method1_cutoff_setting2_simulation(cutoff = .8)
```

```{r}
set.seed(12)
ep_method1_cutoff_.9_setting2_v2 <- run_ep_method1_cutoff_setting2_simulation(cutoff = .9)
```

```{r}
set.seed(12)
ep_method1_cutoff_1_setting2_v2 <- run_ep_method1_cutoff_setting2_simulation(cutoff = 1)
```

