---
title: "ep-BH arbitrary cutoff v2"
author: "Ethan Naegele"
date: "2024-05-26"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(knockoff)
library(pracma)
library(tidyverse)
```

This document runs the same simulations that were in the ep-BH-arbitrary-cutoff-setting1 file but now with a corrected function for the variance parameter estimate, where the linear model does not try to calculate an intercept term. 

```{r}
# making an ep-BH function with arbitrary cutoff, to test the effect of cutoffs better
ep_sarkar_tang_method1_cutoff <- function(X, Y, alpha = .05, cutoff = .2, multiplier = 1.9){
  d <- ncol(X)
  nu <- nrow(X) - 2 * d # n - 2d assuming n > 2d
  T1 <- get_T_1(X, Y, multiplier = multiplier)
  T2 <- get_T_2(X, Y)
  P_t1 <- pf(T1^2, 1, nu, lower.tail = FALSE) # to calculate probabilities with the t^2_n distribution, have to use the F(1, n) distribution
  P_t2 <- pf(T2^2, 1, nu, lower.tail = FALSE)
  E <- as.numeric(P_t1 <= cutoff) / cutoff # vector of e values
  rejected_indices <- ep_BH(P_t2, E, alpha = alpha) # run ep BH at level alpha
  return(rejected_indices)
}
```


```{r}
run_ep_method1_cutoff_simulation <- function(n, d, a, num_true_sigs, alpha = .05, cutoff = .2,
                                             multiplier = 1.9,
                                             num_iter = 300){
  # Sets up the regression problem with specified dimensions and number of true signals, all of which have
  # the same amplitude. 
  fdp_vec <- numeric(num_iter)
pwr_vec <- c(num_iter)
for (m in 1:num_iter){
  feature_indices <- 1:d
  regression <- get_regression_model(n = n, d = d, a = a, num_true_signals = num_true_sigs)
  true_nonzero_indices <- regression$nonzero_indices
  rejected_indices <- ep_sarkar_tang_method1_cutoff(regression$X, regression$Y, alpha = alpha, cutoff = cutoff,
                                                    multiplier = multiplier)
  num_rejections <- length(rejected_indices)
  num_correct_rejections <- length(intersect(rejected_indices, true_nonzero_indices))
  num_false_rejections <- length(intersect(feature_indices[-true_nonzero_indices], rejected_indices))
  fdp_vec[m] <- num_false_rejections / max(num_rejections, 1)
  pwr_vec[m] <- num_correct_rejections / max(length(true_nonzero_indices), 1)
}
fdr <- mean(fdp_vec)
pwr <- mean(pwr_vec)
return(list(fdr = fdr, power = pwr))
}
```



```{r}
run_ep_method1_cutoff_setting1_simulation <- function(a_vec = c(2, 4, 6, 8, 10), 
                                               alpha = .05,
                                               cutoff = .2,
                                               multiplier = 1.9,
                                               num_iter = 500){
result_vec_power <- c()
result_vec_fdr <- c()
for (amp in a_vec){
  result <- run_ep_method1_cutoff_simulation(n = 200,
                                          d = 40,
                                          a = amp, 
                                          num_true_sigs = 8,
                                          alpha = alpha,
                                          cutoff = cutoff,
                                          multiplier = multiplier,
                                          num_iter = num_iter)
  result_vec_power <- c(result_vec_power, result$power)
  result_vec_fdr <- c(result_vec_fdr, result$fdr)
}
return(data.frame(a = a_vec, power = result_vec_power, fdr = result_vec_fdr))
}
```


```{r}
set.seed(12)
ep_method1_cutoff_.1_setting1_v2 <- run_ep_method1_cutoff_setting1_simulation(cutoff = .1)
```

```{r}
set.seed(12)
ep_method1_cutoff_.2_setting1_v2 <- run_ep_method1_cutoff_setting1_simulation(cutoff = .2)
```


```{r}
set.seed(12)
ep_method1_cutoff_.3_setting1_v2 <- run_ep_method1_cutoff_setting1_simulation(cutoff = .3)
```


```{r}
set.seed(12)
ep_method1_cutoff_.4_setting1_v2 <- run_ep_method1_cutoff_setting1_simulation(cutoff = .4)
```

```{r}
set.seed(12)
ep_method1_cutoff_.5_setting1_v2 <- run_ep_method1_cutoff_setting1_simulation(cutoff = .5)
```

```{r}
set.seed(12)
ep_method1_cutoff_.6_setting1_v2 <- run_ep_method1_cutoff_setting1_simulation(cutoff = .6)
```

```{r}
set.seed(12)
ep_method1_cutoff_.7_setting1_v2 <- run_ep_method1_cutoff_setting1_simulation(cutoff = .7)
```


```{r}
set.seed(12)
ep_method1_cutoff_.8_setting1_v2 <- run_ep_method1_cutoff_setting1_simulation(cutoff = .8)
```

```{r}
set.seed(12)
ep_method1_cutoff_.9_setting1_v2 <- run_ep_method1_cutoff_setting1_simulation(cutoff = .9)
```

```{r}
set.seed(12)
ep_method1_cutoff_1_setting1_v2 <- run_ep_method1_cutoff_setting1_simulation(cutoff = 1)
```



# Graphs 



```{r}
# Setting 1 Power
ggplot(ep_method1_cutoff_.05_setting1, aes(x = a, y = power)) + 
  geom_line(color = 'red') +
  geom_point(shape = 4, color = 'red') + 
  scale_y_continuous(limits = c(0, 1)) +
  labs(x = 'Signal Strength - Amplitude', y = 'Simulated Power', title = 'ep Method 1 Setting 2 Results - exponent = 0 (n = 200, d = 40, k = 8)')
```


```{r}
# Setting 2 Power
ggplot(ep_method1_cutoff_.01_setting1, aes(x = a, y = power)) + 
  geom_line(color = 'red') +
  geom_point(shape = 4, color = 'red') + 
  scale_y_continuous(limits = c(0, 1)) +
  labs(x = 'Signal Strength - Amplitude', y = 'Simulated Power', title = 'ep Method 1 Setting 2 Results - exponent = 0 (n = 500, d = 50, k = 10)')
```

```{r}
# Setting 2 Power
ggplot(ep_method1_cutoff_.01_setting1, aes(x = a, y = fdr)) + 
  geom_line(color = 'red') +
  geom_point(shape = 4, color = 'red') + 
  scale_y_continuous(limits = c(0, .15)) +
  labs(x = 'Signal Strength - Amplitude', y = 'Simulated FDR', title = 'ep Method 1 Setting 2 Results - exponent = 0 (n = 500, d = 50, k = 10)')
```


