---
title: "mcc-iid-methods-graph-summary"
author: "Ethan Naegele"
date: "2024-08-17"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# MCC setting summary

```{r}
combined_df_lfl_setting_mcc <- method1_lfl_setting_mcc_v4[5:8,] %>% 
  full_join(method2_lfl_setting_mcc_v4[5:8,] %>% rename(power_method2 = power, fdr_method2 = fdr), by = 'alpha') %>% 
  full_join(ep_moment_method_lfl_setting_mcc_v4[5:8,] %>% rename(power_ep_moment = power, fdr_ep_moment = fdr), by = 'alpha') %>% 
  full_join(ep_moment_method_alternate_lfl_setting_mcc[5:8,] %>% rename(power_ep_moment_alternate = power, fdr_ep_moment_alternate = fdr), by = 'alpha') %>%
  full_join(CKnockoff_lfl_setting_mcc_.5_pwr %>% rename(power_CKnockoff = power, fdr_CKnockoff = fdr), by = 'alpha') %>% 
  full_join(dbh_lfl_setting_mcc[5:8,] %>% rename(power_dbh = power, fdr_dbh = fdr), by = 'alpha')

combined_df_lfl_setting_mcc <- combined_df_lfl_setting_mcc %>% 
  rename(power_method1 = power, fdr_method1 = fdr)
```


```{r}
long_df_lfl_setting_mcc_power <- pivot_longer(combined_df_lfl_setting_mcc, 
                                                          cols = starts_with("power_"), 
                                       names_to = "Method", 
                                       values_to = "Power")

```


```{r}
long_df_lfl_setting_mcc_fdr <- pivot_longer(combined_df_lfl_setting_mcc, 
                                                          cols = starts_with("fdr_"), 
                                       names_to = "Method", 
                                       values_to = "FDR")

```

```{r}
power_plot_summary_lfl_setting_mcc <- ggplot(long_df_lfl_setting_mcc_power, aes(x = alpha, y = Power, color = Method)) +
  geom_line() +
  geom_point(aes(shape = Method)) +
  scale_color_manual(values = c("power_method1" = "green", 
                                "power_method2" = "purple", 
                                'power_ep_moment' = 'red',
                                'power_ep_moment_alternate' = 'orange',
                                'power_CKnockoff' = 'black',
                                'power_dbh' = 'cyan')) +
  scale_shape_manual(values = c(4, 1, 5, 2, 3, 10)) +
  scale_y_continuous(limits = c(0, 1)) + 
  scale_x_continuous(breaks = c(.01, .05, .10, .20)) +
  labs(title = "Simulated Power Across Different Methods (n = 1000, d = 100, k = 10)", x = "Alpha", y = "Simulated Power") +
  theme_minimal()
print(power_plot_summary_lfl_setting_mcc)
ggsave(filename = 'power_plot_summary_lfl_setting_mcc.pdf', plot = power_plot_summary_lfl_setting_mcc)
```

```{r}
fdr_plot_summary_lfl_setting_mcc <- ggplot(long_df_lfl_setting_mcc_fdr, aes(x = alpha, y = FDR, color = Method)) +
  geom_abline(slope = 1, intercept = 0, # Add the y = x line
              linetype = "dashed",      # Make the line dashed
              color = "blue") +
  geom_line() +
  geom_point(aes(shape = Method)) +
 scale_color_manual(values = c("fdr_method1" = "green", 
                                "fdr_method2" = "purple", 
                                'fdr_ep_moment' = 'red',
                                'fdr_ep_moment_alternate' = 'orange',
                                'fdr_CKnockoff' = 'black',
                                'fdr_dbh' = 'cyan')) +
  scale_shape_manual(values = c(4, 1, 5, 2, 3, 10)) +
  scale_y_continuous(limits = c(0, .25)) + 
  scale_x_continuous(breaks = c(.01, .05, .10, .20)) +
  labs(title = "Simulated FDR Across Different Methods - MCC (n = 1000, d = 100, k = 10)", x = "Alpha", y = "Simulated FDR") +
  theme_minimal()
print(fdr_plot_summary_lfl_setting_mcc)
ggsave(filename = 'fdr_plot_summary_lfl_setting_mcc.pdf', plot = fdr_plot_summary_lfl_setting_mcc)
```


# IID setting summary

```{r}
combined_df_lfl_setting_iid <- method1_lfl_setting_iid_v4[5:8,] %>% 
  full_join(method2_lfl_setting_iid_v4[5:8,] %>% rename(power_method2 = power, fdr_method2 = fdr), by = 'alpha') %>% 
  full_join(ep_moment_method_lfl_setting_iid_v4[5:8,] %>% rename(power_ep_moment = power, fdr_ep_moment = fdr), by = 'alpha') %>% 
  full_join(ep_moment_method_alternate_lfl_setting_iid[5:8,] %>% rename(power_ep_moment_alternate = power, fdr_ep_moment_alternate = fdr), by = 'alpha') %>%
  full_join(CKnockoff_lfl_setting_iid[5:8,] %>% rename(power_CKnockoff = power, fdr_CKnockoff = fdr), by = 'alpha') %>% 
  full_join(dbh_lfl_setting_iid[5:8,] %>% rename(power_dbh = power, fdr_dbh = fdr), by = 'alpha')

combined_df_lfl_setting_iid <- combined_df_lfl_setting_iid %>% 
  rename(power_method1 = power, fdr_method1 = fdr)
```


```{r}
long_df_lfl_setting_iid_power <- pivot_longer(combined_df_lfl_setting_iid, 
                                                          cols = starts_with("power_"), 
                                       names_to = "Method", 
                                       values_to = "Power")

```


```{r}
long_df_lfl_setting_iid_fdr <- pivot_longer(combined_df_lfl_setting_iid, 
                                                          cols = starts_with("fdr_"), 
                                       names_to = "Method", 
                                       values_to = "FDR")

```

```{r}
power_plot_summary_lfl_setting_iid <- ggplot(long_df_lfl_setting_iid_power, aes(x = alpha, y = Power, color = Method)) +
  geom_line() +
  geom_point(aes(shape = Method)) +
  scale_color_manual(values = c("power_method1" = "green", 
                                "power_method2" = "purple", 
                                'power_ep_moment' = 'red',
                                'power_ep_moment_alternate' = 'orange',
                                'power_CKnockoff' = 'black',
                                'power_dbh' = 'cyan')) +
  scale_shape_manual(values = c(4, 1, 5, 2, 3, 10)) +
  scale_y_continuous(limits = c(0, 1)) + 
  scale_x_continuous(breaks = c(.01, .05, .10, .20)) +
  labs(title = "Simulated Power Across Different Methods - IID Normal (n = 1000, d = 100, k = 10)", x = "Alpha", y = "Simulated Power") +
  theme_minimal()
print(power_plot_summary_lfl_setting_iid)
ggsave(filename = 'power_plot_summary_lfl_setting_iid.pdf', plot = power_plot_summary_lfl_setting_iid)
```

```{r}
fdr_plot_summary_lfl_setting_iid <- ggplot(long_df_lfl_setting_iid_fdr, aes(x = alpha, y = FDR, color = Method)) +
  geom_abline(slope = 1, intercept = 0, # Add the y = x line
              linetype = "dashed",      # Make the line dashed
              color = "blue") +
  geom_line() +
  geom_point(aes(shape = Method)) +
 scale_color_manual(values = c("fdr_method1" = "green", 
                                "fdr_method2" = "purple", 
                                'fdr_ep_moment' = 'red',
                                'fdr_ep_moment_alternate' = 'orange',
                                'fdr_CKnockoff' = 'black',
                                'fdr_dbh' = 'cyan')) +
  scale_shape_manual(values = c(4, 1, 5, 2, 3, 10)) +
  scale_y_continuous(limits = c(0, .25)) + 
  scale_x_continuous(breaks = c(.01, .05, .10, .20)) +
  labs(title = "Simulated FDR Across Different Methods - IID Normal (n = 1000, d = 100, k = 10)", x = "Alpha", y = "Simulated FDR") +
  theme_minimal()
print(fdr_plot_summary_lfl_setting_iid)
ggsave(filename = "fdr_plot_summary_lfl_setting_iid.pdf", plot = fdr_plot_summary_lfl_setting_iid)
```
