---
title: "Sarkar-Tang-known-sigma"
author: "Ethan Naegele"
date: "2024-07-11"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


sarkar and tang method for when the variance parameter is known (I refer to the variance parameter as $\sigma$ in these documents, but is referred to as $\tau$ in their paper)

```{r}
sarkar_tang_method1_sigma <- function(X, Y, alpha = .05, sigma = 1, multiplier = 1.9){
  # In this setting, sigma is known
  
  d <- ncol(X)
  sigma_mat <- t(X) %*% X
  equi <- create_equicorrelated_mult(X, multiplier = multiplier) # USE THE MODIFIED FUNCTION FOR BETTER MATRIX CONDITION
  D1 <- equi$D
  X_ko1 <- equi$Xk
  two_sigma_minus_D_inv <- solve(2 * sigma_mat - D1)
  beta_hat_1 <- two_sigma_minus_D_inv %*% t(X + X_ko1) %*% Y
  
  D2 <- diag(create.solve_equi(t(X) %*% X))
  X_ko2 <- create.fixed(X, method = 'equi')$Xk
  beta_hat_2 <- solve(D2) %*% t(X - X_ko2) %*% Y # as defined in section 2 of sarkar and tang
 
  beta_hat_1_sds <- sqrt(diag(2 * sigma^2 * two_sigma_minus_D_inv)) # standard deviation of the beta_1 coefficient estimates
  beta_hat_2_sds <- sqrt(diag(2 * sigma^2 * solve(D2))) # standard deviation of the beta_2 coefficient estimates
  z_scores_1 <- beta_hat_1 / beta_hat_1_sds
  z_scores_2 <- beta_hat_2 / beta_hat_2_sds
  P_t1 <- 2 * (1 - pnorm(abs(z_scores_1)))
  P_t2 <- 2 * (1 - pnorm(abs(z_scores_2)))

  P_tilde <- numeric(d)
  for (j in 1:d){
    if (P_t1[j] > sqrt(alpha)){
      P_tilde[j] <- 1
    }
    else{
      P_tilde[j] <- P_t2[j]
    }
  }
  P_tilde_BH <- p.adjust(P_tilde, method = "BH")
  rejected_indices <- which(P_tilde_BH <= sqrt(alpha))
  return(rejected_indices) # the indices of the features that the test concludes are nonzero
  
}
```


