---
title: "Sarkar and Tang knockoffs baseline"
author: "Ethan Naegele"
date: "2024-05-07"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
knockoff_procedure <- function(X, Y, alpha = .05, method = 'equi'){
  # First, need to run create.fixed to get the knockoff matrix
  # Then, need to run the function stat.lasso_lambdasmax to generate the statistics
  # then, need to run knockoff.threshold to compute the knockoff threshold given the test statistics
  # Then, need to determine which variables to keep and which ones to exclude in the model (the ones above the threshold need to be kept in the model)
  # method is either 'equi' or 'sdp'
  #X_ko <- create.fixed(X, method = method)$Xk
  #test_statistics <- stat.glmnet_lambdasmax(X, X_ko, as.vector(Y), family = 'gaussian')
  #threshold <- knockoff.threshold(W = test_statistics, fdr = alpha, offset = 1) # offset 1 to run knockoff+
  #kept_feature_indices <- which(test_statistics >= threshold) # indices of the features to keep in the model
  #return(kept_feature_indices)
  return(knockoff.filter(X, 
                as.vector(Y), 
                knockoffs = function(Z) create.fixed(Z, method = method), 
                statistic = stat.lasso_lambdasmax,
                fdr = alpha,
                offset = 1)$selected)
  
}
```

```{r}
set.seed(12)
regression <- get_regression_model(n= 1000, d = 100, a = 4, num_true_signals = 20)
result <- knockoff.filter(regression$X, 
                as.vector(regression$Y), 
                knockoffs = function(X) create.fixed(X ,method = 'equi'), 
                statistic = stat.lasso_lambdasmax,
                fdr = .05,
                offset = 1)
```



```{r}

regression <- get_regression_model(n= 1000, d = 100, a = 5, num_true_signals = 20)
knockoff_procedure(regression$X, regression$Y)
result <- knockoff.filter(regression$X, 
                as.vector(regression$Y), 
                knockoffs = function(X) create.fixed(X ,method = 'equi'), 
                statistic = stat.lasso_lambdasmax,
                fdr = .05,
                offset = 1)
result$selected
```






```{r}
run_knockoffs_simulation <- function(n, d, a, num_true_sigs, alpha = .05, num_iter = 300){
  # Sets up the regression problem with specified dimensions and number of true signals, all of which have
  # the same amplitude. 
  # Runs the simulation by generating the regression problems and then runs fixed X knockoffs as described in Barber and Candes.
  
  
  fdp_vec <- numeric(num_iter)
pwr_vec <- c(num_iter)
for (m in 1:num_iter){
  feature_indices <- 1:d
  regression <- get_regression_model(n = n, d = d, a = a, num_true_signals = num_true_sigs)
  true_nonzero_indices <- regression$nonzero_indices
  rejected_indices <- knockoff_procedure(regression$X, 
                                         regression$Y, 
                                         alpha = alpha, 
                                         method = 'equi')
  num_rejections <- length(rejected_indices)
  num_correct_rejections <- length(intersect(rejected_indices, true_nonzero_indices))
  num_false_rejections <- length(intersect(feature_indices[-true_nonzero_indices], rejected_indices))
  fdp_vec[m] <- num_false_rejections / max(num_rejections, 1)
  pwr_vec[m] <- num_correct_rejections / max(length(true_nonzero_indices), 1)
}
fdr <- mean(fdp_vec)
pwr <- mean(pwr_vec)
return(list(fdr = fdr, power = pwr))
}
```


# Running the simulations with knockoffs

```{r}
set.seed(12)
# running setting 1 as specified in the paper
result_vec_power_knockoffs_setting1 <- c()
result_vec_fdr_knockoffs_setting1 <- c()
for (amp in c(2, 4, 6, 8, 10)){
  result <- run_knockoffs_simulation(n = 200,
                                          d = 40,
                                          a = amp, 
                                          num_true_sigs = 8,
                                          alpha = .05,
                                          num_iter = 500)
  result_vec_power_knockoffs_setting1 <- c(result_vec_power_knockoffs_setting1, result$power)
  result_vec_fdr_knockoffs_setting1<- c(result_vec_fdr_knockoffs_setting1, result$fdr)
}

```


```{r}
knockoffs_setting1 <- data.frame(a = c(2, 4, 6, 8, 10), 
                                         power = result_vec_power_knockoffs_setting1, 
                                         fdr = result_vec_fdr_knockoffs_setting1)
```



```{r}
set.seed(12)
# running setting 2 as specified in the paper
result_vec_power_knockoffs_setting2 <- c()
result_vec_fdr_knockoffs_setting2 <- c()
for (amp in c(2, 4, 6, 8, 10)){
  result <- run_knockoffs_simulation(n = 500,
                                          d = 50,
                                          a = amp, 
                                          num_true_sigs = 10, 
                                          alpha = .05,
                                          num_iter = 500)
  result_vec_power_knockoffs_setting2 <- c(result_vec_power_knockoffs_setting2, result$power)
  result_vec_fdr_knockoffs_setting2<- c(result_vec_fdr_knockoffs_setting2, result$fdr)
}

```

```{r}
knockoffs_setting2 <- data.frame(a = c(2, 4, 6, 8, 10), 
                                         power = result_vec_power_knockoffs_setting2, 
                                         fdr = result_vec_fdr_knockoffs_setting2)
```

```{r}
set.seed(12)
# running setting 3 as specified in the paper
result_vec_power_knockoffs_setting3 <- c()
result_vec_fdr_knockoffs_setting3 <- c()
for (amp in c(2, 4, 6, 8, 10)){
  result <- run_knockoffs_simulation(n = 1000,
                                          d = 100,
                                          a = amp, 
                                          num_true_sigs = 20,
                                          alpha = .05,
                                          num_iter = 500)
  result_vec_power_knockoffs_setting3 <- c(result_vec_power_knockoffs_setting3, result$power)
  result_vec_fdr_knockoffs_setting3 <- c(result_vec_fdr_knockoffs_setting3, result$fdr)
}

```


```{r}
knockoffs_setting3 <- data.frame(a = c(2, 4, 6, 8, 10), 
                                         power = result_vec_power_knockoffs_setting3, 
                                         fdr = result_vec_fdr_knockoffs_setting3)
```




# Graphs for knockoffs


```{r}
# Setting 1 Power
ggplot(knockoffs_setting1, aes(x = a, y = power)) + 
  geom_line(color = 'red') +
  geom_point(shape = 4, color = 'red') + 
  scale_y_continuous(limits = c(0, 1)) +
  labs(x = 'Signal Strength - Amplitude', y = 'Simulated Power', title = 'Knockoffs Setting 1 Results (n = 200, d = 40, k = 8)')
```



```{r}
# Setting 1 FDR
ggplot(knockoffs_setting1, aes(x = a, y = fdr)) + 
  geom_line(color = 'red') +
  geom_point(shape = 4, color = 'red') + 
  scale_y_continuous(limits = c(0, .15)) +
  labs(x = 'Signal Strength - Amplitude', y = 'Simulated FDR', title = 'Knockoffs Setting 1 Results (n = 200, d = 40, k = 8)')
```


```{r}
# Setting 2 power
ggplot(knockoffs_setting2, aes(x = a, y = power)) + 
  geom_line(color = 'red') +
  geom_point(shape = 4, color = 'red') + 
  scale_y_continuous(limits = c(0, 1)) +
  labs(x = 'Signal Strength - Amplitude', y = 'Simulated Power', title = 'Knockoffs Setting 2 Results (n = 500, d = 50, k = 10)')
```



```{r}
# Setting 2 FDR
ggplot(knockoffs_setting2, aes(x = a, y = fdr)) + 
  geom_line(color = 'red') +
  geom_point(shape = 4, color = 'red') + 
  scale_y_continuous(limits = c(0, .15)) +
  labs(x = 'Signal Strength - Amplitude', y = 'Simulated FDR', title = 'Knockoffs Setting 2 Results (n = 500, d = 50, k = 10)')
```


```{r}
# Setting 3 power
ggplot(knockoffs_setting3, aes(x = a, y = power)) + 
  geom_line(color = 'red') +
  geom_point(shape = 4, color = 'red') + 
  scale_y_continuous(limits = c(0, 1)) +
  labs(x = 'Signal Strength - Amplitude', y = 'Simulated Power', title = 'Knockoffs Setting 3 Results (n = 1000, d = 100, k = 20)')
```


```{r}
# Setting 3 FDR
ggplot(knockoffs_setting3, aes(x = a, y = fdr)) + 
  geom_line(color = 'red') +
  geom_point(shape = 4, color = 'red') + 
  scale_y_continuous(limits = c(0, .15)) +
  labs(x = 'Signal Strength - Amplitude', y = 'Simulated FDR', title = 'Knockoffs Setting 3 Results (n = 1000, d = 100, k = 20)')
```









