---
title: "Sarkar and Tang method 2"
author: "Ethan Naegele"
date: "2024-05-04"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Method 2 from Sarkar and Tang

```{r}
sarkar_tang_method2 <- function(X, Y, alpha = .05, eta = .7){
  d <- ncol(X)
  nu <- nrow(X) - 2 * d # n - 2d assuming n > 2d
  T1 <- get_T_1(X, Y)
  T2 <- get_T_2(X, Y)
  P_t1 <- pf(T1^2, 1, nu, lower.tail = FALSE) # to calculate probabilities with the t^2_n distribution, have to use the F(1, n) distribution
  P_t2 <- pf(T2^2, 1, nu, lower.tail = FALSE)
  pi_0_hat <- (d - sum(as.numeric(P_t2 <= eta)) + 1) / (d * (1 - eta)) # Storey-type null proportion estimate in Step 2
  P_star <- numeric(d)
  for (j in 1:d){
    if (P_t1[j] > sqrt(alpha)){
      P_star[j] <- 1
    }
    else{
      P_star[j] <- P_t2[j] * pi_0_hat
    }
  }
  P_star_BH <- p.adjust(P_star, method = "BH")
  rejected_indices <- which(P_star_BH <= sqrt(alpha))
  return(rejected_indices) # the indices of the features that the test concludes are nonzero
  
}
```


```{r}
run_method2_simulation <- function(n, d, a, num_true_sigs, eta = .7, num_iter = 300){
  # Sets up the regression problem with specified dimensions and number of true signals, all of which have
  # the same amplitude. 
  fdp_vec <- numeric(num_iter)
pwr_vec <- c(num_iter)
for (m in 1:num_iter){
  feature_indices <- 1:d
  regression <- get_regression_model(n = n, d = d, a = a, num_true_signals = num_true_sigs)
  true_nonzero_indices <- regression$nonzero_indices
  rejected_indices <- sarkar_tang_method2(regression$X, regression$Y, alpha = .05, eta = eta)
  num_rejections <- length(rejected_indices)
  num_correct_rejections <- length(intersect(rejected_indices, true_nonzero_indices))
  num_false_rejections <- length(intersect(feature_indices[-true_nonzero_indices], rejected_indices))
  fdp_vec[m] <- num_false_rejections / max(num_rejections, 1)
  pwr_vec[m] <- num_correct_rejections / max(length(true_nonzero_indices), 1)
}
fdr <- mean(fdp_vec)
pwr <- mean(pwr_vec)
return(list(fdr = fdr, power = pwr))
}
```



## Running method 2 simulations

```{r}
set.seed(12)
# running setting 1 as specified in the paper
result_vec_power_method2_setting1 <- c()
result_vec_fdr_method2_setting1 <- c()
for (amp in c(2, 4, 6, 8, 10)){
  result <- run_method2_simulation(n = 200,
                                          d = 40,
                                          a = amp, 
                                          num_true_sigs = 8,
                                          eta = .5,
                                          num_iter = 500)
  result_vec_power_method2_setting1 <- c(result_vec_power_method2_setting1, result$power)
  result_vec_fdr_method2_setting1<- c(result_vec_fdr_method2_setting1, result$fdr)
}

```


```{r}
method2_setting1 <- data.frame(a = c(2, 4, 6, 8, 10), 
                                         power = result_vec_power_method2_setting1, 
                                         fdr = result_vec_fdr_method2_setting1)
```



```{r}
set.seed(12)
# running setting 2 as specified in the paper
result_vec_power_method2_setting2 <- c()
result_vec_fdr_method2_setting2 <- c()
for (amp in c(2, 4, 6, 8, 10)){
  result <- run_method2_simulation(n = 500,
                                          d = 50,
                                          a = amp, 
                                          num_true_sigs = 10, 
                                          eta = .5,
                                          num_iter = 500)
  result_vec_power_method2_setting2 <- c(result_vec_power_method2_setting2, result$power)
  result_vec_fdr_method2_setting2<- c(result_vec_fdr_method2_setting2, result$fdr)
}

```


```{r}
method2_setting2 <- data.frame(a = c(2, 4, 6, 8, 10), 
                                         power = result_vec_power_method2_setting2, 
                                         fdr = result_vec_fdr_method2_setting2)
```



```{r}
set.seed(12)
# running setting 3 as specified in the paper
result_vec_power_method2_setting3 <- c()
result_vec_fdr_method2_setting3 <- c()
for (amp in c(2, 4, 6, 8, 10)){
  result <- run_method2_simulation(n = 1000,
                                          d = 100,
                                          a = amp, 
                                          num_true_sigs = 20,
                                          eta = .5,
                                          num_iter = 500)
  result_vec_power_method2_setting3 <- c(result_vec_power_method2_setting3, result$power)
  result_vec_fdr_method2_setting3 <- c(result_vec_fdr_method2_setting3, result$fdr)
}

```


```{r}
method2_setting3 <- data.frame(a = c(2, 4, 6, 8, 10), 
                                         power = result_vec_power_method2_setting3, 
                                         fdr = result_vec_fdr_method2_setting3)
```




## Graphs for Method 2

```{r}
# Setting 1 Power
ggplot(method2_setting1, aes(x = a, y = power)) + 
  geom_line(color = 'red') +
  geom_point(shape = 4, color = 'red') + 
  scale_y_continuous(limits = c(0, 1)) +
  labs(x = 'Signal Strength - Amplitude', y = 'Simulated Power', title = 'Method 2 Setting 1 Results (n = 200, d = 40, k = 8)')
```


```{r}
# Setting 1 FDR
ggplot(method2_setting1, aes(x = a, y = fdr)) + 
  geom_line(color = 'red') +
  geom_point(shape = 4, color = 'red') + 
  scale_y_continuous(limits = c(0, .15)) +
  labs(x = 'Signal Strength - Amplitude', y = 'Simulated FDR', title = 'Method 2 Setting 1 Results (n = 200, d = 40, k = 8)')
```


```{r}
# Setting 2 power
ggplot(method2_setting2, aes(x = a, y = power)) + 
  geom_line(color = 'red') +
  geom_point(shape = 4, color = 'red') + 
  scale_y_continuous(limits = c(0, 1)) +
  labs(x = 'Signal Strength - Amplitude', y = 'Simulated Power', title = 'Method 2 Setting 2 Results (n = 500, d = 50, k = 10)')
```


```{r}
# Setting 2 FDR
ggplot(method2_setting2, aes(x = a, y = fdr)) + 
  geom_line(color = 'red') +
  geom_point(shape = 4, color = 'red') + 
  scale_y_continuous(limits = c(0, .15)) +
  labs(x = 'Signal Strength - Amplitude', y = 'Simulated FDR', title = 'Method 2 Setting 2 Results (n = 500, d = 50, k = 10)')
```


```{r}
# Setting 3 Power
ggplot(method2_setting3, aes(x = a, y = power)) + 
  geom_line(color = 'red') +
  geom_point(shape = 4, color = 'red') + 
  scale_y_continuous(limits = c(0, 1)) +
  labs(x = 'Signal Strength - Amplitude', y = 'Simulated Power', title = 'Method 2 Setting 3 Results (n = 1000, d = 100, k = 20)')
```


```{r}
# Setting 3 FDR
ggplot(method2_setting3, aes(x = a, y = fdr)) + 
  geom_line(color = 'red') +
  geom_point(shape = 4, color = 'red') + 
  scale_y_continuous(limits = c(0, .15)) +
  labs(x = 'Signal Strength - Amplitude', y = 'Simulated FDR', title = 'Method 2 Setting 3 Results (n = 1000, d = 100, k = 20)')
```



