---
title: "Sarkar Tang knockoffs baseline v2"
author: "Ethan Naegele"
date: "2024-06-20"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(knockoff)
library(pracma)
library(tidyverse)
```

This document runs the same simulations that were in the Sarkar-Tang-knockoffs baseline file but now with a corrected function for the variance parameter estimate, where the linear model does not try to calculate an intercept term. We also run the simulations using wrapper functions to save space. 


```{r}
knockoff_procedure <- function(X, Y, alpha = .05, method = 'equi'){
  return(knockoff.filter(X, 
                as.vector(Y), 
                knockoffs = function(Z) create.fixed(Z, method = method), 
                statistic = stat.lasso_lambdasmax,
                fdr = alpha,
                offset = 1)$selected) # offset 1 to run knockoff+
  
}
```


```{r}
run_knockoffs_simulation <- function(n, d, a, num_true_sigs, alpha = .05, num_iter = 300){
  # Sets up the regression problem with specified dimensions and number of true signals, all of which have
  # the same amplitude. 
  # Runs the simulation by generating the regression problems and then runs fixed X knockoffs as described in Barber and Candes.
  
  
  fdp_vec <- numeric(num_iter)
pwr_vec <- c(num_iter)
for (m in 1:num_iter){
  feature_indices <- 1:d
  regression <- get_regression_model(n = n, d = d, a = a, num_true_signals = num_true_sigs)
  true_nonzero_indices <- regression$nonzero_indices
  rejected_indices <- knockoff_procedure(regression$X, 
                                         regression$Y, 
                                         alpha = alpha, 
                                         method = 'equi')
  num_rejections <- length(rejected_indices)
  num_correct_rejections <- length(intersect(rejected_indices, true_nonzero_indices))
  num_false_rejections <- length(intersect(feature_indices[-true_nonzero_indices], rejected_indices))
  fdp_vec[m] <- num_false_rejections / max(num_rejections, 1)
  pwr_vec[m] <- num_correct_rejections / max(length(true_nonzero_indices), 1)
}
fdr <- mean(fdp_vec)
pwr <- mean(pwr_vec)
return(list(fdr = fdr, power = pwr))
}
```


```{r}
run_knockoffs_setting1_simulation <- function(a_vec = c(2, 4, 6, 8, 10), 
                                              alpha = .05,
                                               num_iter = 500){
result_vec_power <- c()
result_vec_fdr <- c()
for (amp in a_vec){
  result <- run_knockoffs_simulation(n = 200,
                                          d = 40,
                                          a = amp,
                                          alpha = alpha,
                                          num_true_sigs = 8,
                                          num_iter = num_iter)
  result_vec_power <- c(result_vec_power, result$power)
  result_vec_fdr <- c(result_vec_fdr, result$fdr)
}
return(data.frame(a = a_vec, power = result_vec_power, fdr = result_vec_fdr))
}
```


```{r}
run_knockoffs_setting2_simulation <- function(a_vec = c(2, 4, 6, 8, 10), 
                                              alpha = .05,
                                               num_iter = 500){
result_vec_power <- c()
result_vec_fdr <- c()
for (amp in a_vec){
  result <- run_knockoffs_simulation(n = 500,
                                          d = 50,
                                          a = amp,
                                          alpha = alpha,
                                          num_true_sigs = 10,
                                          num_iter = num_iter)
  result_vec_power <- c(result_vec_power, result$power)
  result_vec_fdr <- c(result_vec_fdr, result$fdr)
}
return(data.frame(a = a_vec, power = result_vec_power, fdr = result_vec_fdr))
}
```


```{r}
run_knockoffs_setting3_simulation <- function(a_vec = c(2, 4, 6, 8, 10), 
                                              alpha = .05,
                                               num_iter = 500){
result_vec_power <- c()
result_vec_fdr <- c()
for (amp in a_vec){
  result <- run_knockoffs_simulation(n = 1000,
                                          d = 100,
                                          a = amp,
                                          alpha = alpha,
                                          num_true_sigs = 20,
                                          num_iter = num_iter)
  result_vec_power <- c(result_vec_power, result$power)
  result_vec_fdr <- c(result_vec_fdr, result$fdr)
}
return(data.frame(a = a_vec, power = result_vec_power, fdr = result_vec_fdr))
}
```

```{r}
set.seed(12)
knockoffs_setting1_v2 <- run_knockoffs_setting1_simulation()
```

```{r}
set.seed(12)
knockoffs_setting2_v2 <- run_knockoffs_setting2_simulation()
```

```{r}
set.seed(12)
knockoffs_setting3_v2 <- run_knockoffs_setting3_simulation()
```

